global using System.Diagnostics;
global using System.Net;
global using System.Net.Http.Headers;
global using System.Runtime.CompilerServices;
global using System.Text;
global using System.Text.Json;
global using Bunit;
global using NUnit.Framework;
global using TestContext = NUnit.Framework.TestContext;
global using VerifyTests.DiffPlex;
global using BlazorQL;
global using static VerifyNUnit.Verifier;
global using GraphQL;
global using GraphQL.Execution;
global using GraphQL.Resolvers;
global using GraphQL.SystemTextJson;
global using GraphQL.Types;
global using GraphQL.Validation;
global using System.Text.RegularExpressions;
