global using System.Runtime.CompilerServices;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using System.Threading.Channels;
global using GraphQL;
global using GraphQL.SystemTextJson;
global using GraphQL.Execution;
global using GraphQL.Resolvers;
global using GraphQL.Types;
